---
apiVersion: logging.opstreelabs.in/v1alpha1
kind: Kibana
metadata:
  name: kibana
  labels:
    organization: opstree
    owned-by: Abhishek
  namespace: logging-operator
spec:
  image: docker.elastic.co/kibana/kibana:7.8.0
  imagePullPolicy: "IfNotPresent"
  elasticsearch:
    host: "elasticsearch-cluster-ingestion"
    username: elastic
    password: "Opstree@1234"
    tlsEnabled: false
  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 100m
      memory: 200Mi
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - "kibana"
        topologyKey: kubernetes.io/hostname
