site_name: Logging Operator
theme:
  name: material
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - tabs

site_author: Opstree Solutions
site_description: >
  A golang based CRD operator to setup and manage logging 
  (Elasticsearch, Fluentd and Kibana) in Kubernetes cluster. 
  It helps to setup each component of EFK stack separately.

repo_name: ot-container-kit/logging-operator
repo_url: https://github.com/ot-container-kit/logging-operator

copyright: Copyright - 2020 Opstree Solutions

nav:
  - Home: index.md
