---
elasticsearch:
  name: prod-cluster

  cluster_name: "production"

  image:
    name: docker.elastic.co/elasticsearch/elasticsearch
    tag: "7.8.0"
    imagePullPolicy: IfNotPresent

  security:
    enabled: true
    password: "Opstree@1234"

  plugins:
    - repository-s3

  master:
    enabled: true
    replicas: 3

    resources: {}
      # requests:
      #   cpu: 1000m
      #   memory: 1Gi
      # limits:
      #   cpu: 1000m
      #   memory: 1Gi
    jvmMax: "1g"
    jvmMin: "1g"

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - "elasticsearch-cluster-master"
          topologyKey: kubernetes.io/hostname

    storageSpec: {}
      # volumeClaimTemplate:
      #   spec:
      #     storageClassName: standard
      #     accessModes: ["ReadWriteOnce"]
      #     resources:
      #       requests:
      #         storage: 1Gi
      #   selector: {}

  master:
    enabled: true
    replicas: 3

    resources: {}
      # requests:
      #   cpu: 1000m
      #   memory: 1Gi
      # limits:
      #   cpu: 1000m
      #   memory: 1Gi
    jvmMax: "1g"
    jvmMin: "1g"

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - "elasticsearch-cluster-master"
          topologyKey: kubernetes.io/hostname

    storageSpec: {}
      # volumeClaimTemplate:
      #   spec:
      #     storageClassName: standard
      #     accessModes: ["ReadWriteOnce"]
      #     resources:
      #       requests:
      #         storage: 1Gi
      #   selector: {}

  data:
    enabled: true
    replicas: 3

    resources: {}
      # requests:
      #   cpu: 1000m
      #   memory: 1Gi
      # limits:
      #   cpu: 1000m
      #   memory: 1Gi
    jvmMax: "1g"
    jvmMin: "1g"

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - "elasticsearch-cluster-data"
          topologyKey: kubernetes.io/hostname

    storageSpec: {}
      # volumeClaimTemplate:
      #   spec:
      #     storageClassName: standard
      #     accessModes: ["ReadWriteOnce"]
      #     resources:
      #       requests:
      #         storage: 1Gi
      #   selector: {}

  ingestion:
    enabled: true
    replicas: 3

    resources: {}
      # requests:
      #   cpu: 1000m
      #   memory: 1Gi
      # limits:
      #   cpu: 1000m
      #   memory: 1Gi
    jvmMax: "1g"
    jvmMin: "1g"

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - "elasticsearch-cluster-ingestion"
          topologyKey: kubernetes.io/hostname

    storageSpec: {}
      # volumeClaimTemplate:
      #   spec:
      #     storageClassName: standard
      #     accessModes: ["ReadWriteOnce"]
      #     resources:
      #       requests:
      #         storage: 1Gi
      #   selector: {}

  client:
    enabled: true
    replicas: 3

    resources: {}
      # requests:
      #   cpu: 1000m
      #   memory: 1Gi
      # limits:
      #   cpu: 1000m
      #   memory: 1Gi
    jvmMax: "1g"
    jvmMin: "1g"

    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
            - key: app
              operator: In
              values:
              - "elasticsearch-cluster-client"
          topologyKey: kubernetes.io/hostname

    storageSpec: {}
      # volumeClaimTemplate:
      #   spec:
      #     storageClassName: standard
      #     accessModes: ["ReadWriteOnce"]
      #     resources:
      #       requests:
      #         storage: 1Gi
      #   selector: {}

fluentd:
  name: fluentd

  image:
    name: fluent/fluentd-kubernetes-daemonset
    tag: v1-debian-elasticsearch
    imagePullPolicy: IfNotPresent

  nodeSelector: {}
    # kubernetesWorker: "true"
  
  logPrefix: namespace

  resources:
    requests:
      cpu: 100m
      memory: 200Mi
    limits:
      cpu: 100m
      memory: 200Mi

  elasticsearch:
    host: elasticsearch-cluster-ingestion
    username: elastic
    password: Opstree@1234
    tlsEnabled: true

kibana:
  name: kibana
  
  replicas: 1

  image:
    name: docker.elastic.co/kibana/kibana
    tag: "7.8.0"
    imagePullPolicy: IfNotPresent

  elasticsearch:
    host: elasticsearch-cluster-ingestion
    username: elastic
    password: Opstree@1234
    tlsEnabled: true

  resources:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: 1000m
      memory: 1Gi

  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - "kibana"
        topologyKey: kubernetes.io/hostname
