---
version: 2
jobs:
  code-quality:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/logging-operator
    steps:
      - checkout
      - run: make fmt
      - run: make vet

  code-build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/logging-operator
    steps:
      - checkout
      - run: make manager

  image-build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/logging-operator
    steps:
      - checkout
      - setup_remote_docker
      - run: make bundle-build

  k8s-validation:
    machine:
      image: circleci/classic:201808-01
    environment:
      K8S_VERSION: v1.15.7
      HELM_VERSION: v3.1.0
      KUBECONFIG: /home/circleci/.kube/config
      MINIKUBE_VERSION: v1.7.3
      MINIKUBE_WANTUPDATENOTIFICATION: false
      MINIKUBE_WANTREPORTERRORPROMPT: false
      MINIKUBE_HOME: /home/circleci
      CHANGE_MINIKUBE_NONE_USER: true
    steps:
      - checkout
      - run:
          name: Setup kubectl
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${K8S_VERSION}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
            mkdir -p ${HOME}/.kube
            touch ${HOME}/.kube/config
      - run:
          name: Setup minikube
          command: |
            curl -Lo minikube https://github.com/kubernetes/minikube/releases/download/${MINIKUBE_VERSION}/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
      - run:
          name: Start minikube
          command: |
            sudo -E minikube start --vm-driver=none --cpus 2 --memory 2048 --kubernetes-version=${K8S_VERSION}
      - run:
          name: Setup helm
          command: |
            curl -Lo helm-${HELM_VERSION}-linux-amd64.tar.gz https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz \
            && tar -xvzf helm-${HELM_VERSION}-linux-amd64.tar.gz && chmod +x linux-amd64/helm \
            && sudo mv linux-amd64/helm /usr/local/bin/
      - run:
          name: Setup Namespace
          command: |
            kubectl create namespace logging-operator
      - run:
          name: Validating logging operator
          command: |
            ./scripts/k8s-validate.sh

workflows:
  version: 2
  main:
    jobs:
      - code-quality
      - code-build
      - image-build
      - k8s-validation
