apiVersion: v2
appVersion: "0.1.0"
description: "Logging Operator: EFK stack running on Kubernetes"
name: logging-operator
version: 0.1.0
icon: https://raw.githubusercontent.com/ot-container-kit/logging-operator/master/static/logging-operator-logo.svg
keywords:
  - elasticsearch
  - fluentd
  - kibana
  - searching
  - kubernetes
home: https://ot-container-kit.github.io/logging-operator
sources:
- https://github.com/ot-container-kit/logging-operator
maintainers:
- name: Abhishek Dubey
- name: Sandeep Rawat
