{{- if .Values.elasticsearch.enabled }}
---
apiVersion: logging.opstreelabs.in/v1alpha1
kind: Elasticsearch
metadata:
  name: {{ .Values.elasticsearch.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  clusterName: "{{ .Values.elasticsearch.cluster_name }}"
  image: "{{ .Values.elasticsearch.image.name }}:{{ .Values.elasticsearch.image.tag }}"
  imagePullPolicy: "{{ .Values.elasticsearch.image.imagePullPolicy }}"
  security:
    tlsEnabled: {{ .Values.elasticsearch.security.enabled }}
    password: "{{ .Values.elasticsearch.security.password }}"
  plugins:
{{ range .Values.elasticsearch.plugins }}
    - {{ . }}
{{- end }}
  master:
    enabled: {{ .Values.elasticsearch.master.enabled }}
    count: {{ .Values.elasticsearch.master.replicas }}
{{- if .Values.elasticsearch.master.resources }}
    resources:
{{ toYaml .Values.elasticsearch.master.resources | indent 6 }}
{{- end }}
{{- if .Values.elasticsearch.master.storageSpec }}
  storage:
{{ toYaml .Values.elasticsearch.master.storageSpec | indent 4 }}
{{- end }}
    jvmOptions:
      Xmx: "{{ .Values.elasticsearch.master.jvmMax }}"
      Xms: "{{ .Values.elasticsearch.master.jvmMin }}"
{{- if .Values.elasticsearch.master.affinity }}
    affinity:
{{ toYaml .Values.elasticsearch.master.affinity | indent 6 }}
{{- end }}
  data:
    enabled: {{ .Values.elasticsearch.data.enabled }}
    count: {{ .Values.elasticsearch.data.replicas }}
{{- if .Values.elasticsearch.data.resources }}
    resources:
{{ toYaml .Values.elasticsearch.data.resources | indent 6 }}
{{- end }}
{{- if .Values.elasticsearch.data.storageSpec }}
  storage:
{{ toYaml .Values.elasticsearch.data.storageSpec | indent 4 }}
{{- end }}
    jvmOptions:
      Xmx: "{{ .Values.elasticsearch.data.jvmMax }}"
      Xms: "{{ .Values.elasticsearch.data.jvmMin }}"
{{- if .Values.elasticsearch.data.affinity }}
    affinity:
{{ toYaml .Values.elasticsearch.data.affinity | indent 6 }}
{{- end }}
  ingestion:
    enabled: {{ .Values.elasticsearch.ingestion.enabled }}
    count: {{ .Values.elasticsearch.ingestion.replicas }}
{{- if .Values.elasticsearch.ingestion.resources }}
    resources:
{{ toYaml .Values.elasticsearch.ingestion.resources | indent 6 }}
{{- end }}
{{- if .Values.elasticsearch.ingestion.storageSpec }}
  storage:
{{ toYaml .Values.elasticsearch.ingestion.storageSpec | indent 4 }}
{{- end }}
    jvmOptions:
      Xmx: "{{ .Values.elasticsearch.ingestion.jvmMax }}"
      Xms: "{{ .Values.elasticsearch.ingestion.jvmMin }}"
{{- if .Values.elasticsearch.ingestion.affinity }}
    affinity:
{{ toYaml .Values.elasticsearch.ingestion.affinity | indent 6 }}
{{- end }}
  client:
    enabled: {{ .Values.elasticsearch.client.enabled }}
    count: {{ .Values.elasticsearch.client.replicas }}
{{- if .Values.elasticsearch.client.resources }}
    resources:
{{ toYaml .Values.elasticsearch.client.resources | indent 6 }}
{{- end }}
{{- if .Values.elasticsearch.client.storageSpec }}
  storage:
{{ toYaml .Values.elasticsearch.client.storageSpec | indent 4 }}
{{- end }}
    jvmOptions:
      Xmx: "{{ .Values.elasticsearch.client.jvmMax }}"
      Xms: "{{ .Values.elasticsearch.client.jvmMin }}"
{{- if .Values.elasticsearch.client.affinity }}
    affinity:
{{ toYaml .Values.elasticsearch.client.affinity | indent 6 }}
{{- end }}
{{- end }}
