---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.name }}"
  labels:
    control-plane: "{{ .Values.name }}"
    app.kubernetes.io/name: {{ .Values.name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
spec:
  selector:
    matchLabels:
      control-plane: "{{ .Values.name }}"
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        control-plane: "{{ .Values.name }}"
    spec:
      containers:
      - command:
        - /manager
        args:
        - --enable-leader-election
        image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
        name: "{{ .Values.name }}"
{{- if .Values.resources }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
{{- end }}
      terminationGracePeriodSeconds: 10
      serviceAccount: "{{ .Values.serviceAccountName }}"
      serviceAccountName: "{{ .Values.serviceAccountName }}"
